version: '3'
services:
  nestjs-service:
    image: ngthminhdev/electric-board-backend:${TAG}
    restart: always
    deploy:
      replicas: 1
    ports: 
      - '3001:3001'
    environment:
      - CONFIG_SERVER_HOST=192.168.9.250
      - CONFIG_SERVER_PORT=3001
      - CONFIG_API_PREFIX=api/v1
      - CONFIG_STRATEGY=jwt
      - CONFIG_WHITELIST_IPS=
      - CONFIG_POSTGRES_HOST=minh.ceakpvhscsux.ap-southeast-1.rds.amazonaws.com
      - CONFIG_POSTGRES_PORT=5432
      - CONFIG_POSTGRES_USERNAME=ngthminhdev
      - CONFIG_POSTGRES_PASSWORD=kimlien0602
      - CONFIG_POSTGRES_DB_NAME=stocks_data
      - CONFIG_SECRET_SIGN_KEY=secret_sign_key
      - CONFIG_ACCESS_TOKEN_SECRET=access_token_secret
      - CONFIG_REFRESH_TOKEN_SECRET=refresh_token_secret
      - CONFIG_REDIS_HOST=13.213.50.191
      - CONFIG_REDIS_PORT=6379
      - CONFIG_REDIS_PASSWORD=redis_aws_ec2_password
      - CONFIG_REDIS_DB=1